//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadWriteDontRush
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookListItems
    {
        public int ListItemID { get; set; }
        public int ListID { get; set; }
        public int BookID { get; set; }
        public System.DateTime AddedAt { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual BookLists BookLists { get; set; }
    }
}
