//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadWriteDontRush
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookListItems
    {
        public int Id { get; set; }
        public int ListId { get; set; }
        public int BookId { get; set; }
        public Nullable<System.DateTime> AddedAt { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual BookLists BookLists { get; set; }
    }
}
