//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadWriteDontRush
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ReadWriteDontRushEntities : DbContext
    {
        public ReadWriteDontRushEntities()
            : base("name=ReadWriteDontRushEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AuthorRequests> AuthorRequests { get; set; }
        public virtual DbSet<BookListItems> BookListItems { get; set; }
        public virtual DbSet<BookLists> BookLists { get; set; }
        public virtual DbSet<Books> Books { get; set; }
        public virtual DbSet<Complaints> Complaints { get; set; }
        public virtual DbSet<ComplaintTypes> ComplaintTypes { get; set; }
        public virtual DbSet<Genres> Genres { get; set; }
        public virtual DbSet<Reviews> Reviews { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<UnfreezeRequests> UnfreezeRequests { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
