//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadWriteDontRush
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserBookLists
    {
        public int UserBookListID { get; set; }
        public int UserID { get; set; }
        public int BookID { get; set; }
        public int ListTypeID { get; set; }
        public Nullable<System.DateTime> AddedAt { get; set; }
    
        public virtual BookListTypes BookListTypes { get; set; }
        public virtual Books Books { get; set; }
        public virtual Users Users { get; set; }
    }
}
